# Generated by Django 4.1.2 on 2022-10-18 19:44

from django.db import migrations
from django.utils import timezone
from blog.models import Blog, Comments
def populate_db(apps,schema_editor):
    
    Blog2Text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in. Risus feugiat in ante metus dictum at tempor commodo. Luctus accumsan tortor posuere ac ut. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Volutpat sed cras ornare arcu. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Imperdiet sed euismod nisi porta lorem mollis. Auctor neque vitae tempus quam pellentesque nec. Turpis cursus in hac habitasse platea dictumst quisque. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Orci a scelerisque purus semper eget duis at tellus. Tellus cras adipiscing enim eu turpis. Tempor id eu nisl nunc mi. Quisque egestas diam in arcu. Amet consectetur adipiscing elit ut aliquam purus. Lectus sit amet est placerat in egestas erat. Adipiscing vitae proin sagittis nisl rhoncus mattis.

Enim ut tellus elementum sagittis vitae et leo duis. Quis viverra nibh cras pulvinar mattis nunc. Cras semper auctor neque vitae. Orci eu lobortis elementum nibh tellus molestie nunc non. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Nulla pharetra diam sit amet nisl. Hac habitasse platea dictumst vestibulum rhoncus est. Libero nunc consequat interdum varius. Dui ut ornare lectus sit. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Integer quis auctor elit sed vulputate mi sit amet. Auctor neque vitae tempus quam. Ipsum a arcu cursus vitae congue. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Ultricies mi eget mauris pharetra et ultrices neque. Non enim praesent elementum facilisis.

Non sodales neque sodales ut etiam sit amet nisl purus. Ligula ullamcorper malesuada proin libero nunc consequat. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Netus et malesuada fames ac. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Velit sed ullamcorper morbi tincidunt ornare massa. In fermentum posuere urna nec tincidunt. A diam sollicitudin tempor id. Nec dui nunc mattis enim ut. Et netus et malesuada fames ac. Ac felis donec et odio pellentesque diam volutpat commodo. Orci a scelerisque purus semper eget duis. Lacus luctus accumsan tortor posuere. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Eget sit amet tellus cras adipiscing enim eu turpis.

Fames ac turpis egestas integer eget aliquet. Ut sem viverra aliquet eget sit amet. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Suspendisse sed nisi lacus sed viverra tellus. Egestas congue quisque egestas diam in arcu cursus euismod. Nibh mauris cursus mattis molestie a iaculis at erat. Vel turpis nunc eget lorem dolor. Arcu dui vivamus arcu felis bibendum ut tristique et. Enim nunc faucibus a pellentesque sit. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Amet luctus venenatis lectus magna fringilla urna porttitor. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Augue neque gravida in fermentum et. Purus in massa tempor nec feugiat nisl pretium fusce.

Nunc non blandit massa enim nec dui. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Turpis nunc eget lorem dolor. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Amet commodo nulla facilisi nullam vehicula ipsum. Fames ac turpis egestas sed tempus urna et. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Bibendum at varius vel pharetra vel turpis nunc eget. Fermentum iaculis eu non diam. Amet massa vitae tortor condimentum lacinia quis vel eros. Amet justo donec enim diam vulputate ut pharetra. Amet massa vitae tortor condimentum lacinia. Nunc sed id semper risus in hendrerit gravida rutrum quisque."""


    comment_sample_text = """ neque sodales ut etiam sit amet nisl purus. Ligula ullamcorper malesuada proin libero nunc consequat. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Netus et malesuada fames ac. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Velit sed ullamcorper morbi tincidunt ornare massa. In fermentum posuere urna nec tinc"""

    blog1 = Blog(id =1 ,title = "Wow I love the godfather", author = "Tony Soprano", content = Blog2Text, posted = timezone.now())
    
    blog1.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog1.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog1.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog1.save()

    blog2 = Blog(id = 2, title = "Just When I Thought I Was Out", author = "Tony Soprano", content = Blog2Text, posted = timezone.now())
    blog2.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog2.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog2.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())

    blog2.save()

    blog3 = Blog(id = 3,title = "Don't you just love mobsters", author = "Tony Soprano", content = Blog2Text, posted = timezone.now())
    blog3.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog3.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog3.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog3.save()

    blog4 = Blog(id = 4, title = "You Guy's Ever Seen Goodfellas", author = "Tony Soprano", content = Blog2Text, posted = timezone.now())
    blog4.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog4.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())
    blog4.comments_set.create(commenter = "Tony Soprano", email = "tony@email.com", content = comment_sample_text, posted = timezone.now())

    blog4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(populate_db)
    ]

