# Generated by Django 4.1.2 on 2022-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='posted',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
